version: '3.8'
name: iceberg-bank-recon

services:
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile.master
    container_name: spark-master
    ports:
      - "8082:8080"  # Spark master UI (using 8082 to avoid conflicts)
      - "7077:7077"  # Spark master port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./src:/opt/bitnami/spark/src
      - ./notebooks:/opt/bitnami/spark/notebooks
      - ./scripts:/opt/bitnami/spark/scripts
      - ./docker/spark/conf:/opt/bitnami/spark/conf
    networks:
      - iceberg-network

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile.worker
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8083:8081"  # Spark worker UI (using 8083 to avoid conflicts)
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./src:/opt/bitnami/spark/src
      - ./scripts:/opt/bitnami/spark/scripts
      - ./docker/spark/conf:/opt/bitnami/spark/conf
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    networks:
      - iceberg-network

  jupyter:
    build:
      context: ./spark
      dockerfile: Dockerfile.jupyter
    container_name: jupyter
    depends_on:
      - spark-master
    ports:
      - "8889:8888"  # Jupyter notebook (using 8889 to avoid conflicts)
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./src:/opt/bitnami/spark/src
      - ./notebooks:/opt/bitnami/spark/notebooks
      - ./scripts:/opt/bitnami/spark/scripts
      - ./docker/spark/conf:/opt/bitnami/spark/conf
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
    networks:
      - iceberg-network

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=iceberg
      - POSTGRES_PASSWORD=iceberg
      - POSTGRES_DB=iceberg_catalog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - iceberg-network

networks:
  iceberg-network:
    driver: bridge

volumes:
  postgres-data:
